title: "Trinary"
excerpt: "Ternary logic and ternary computers"
description: >
  Development of ternary computer systems, information processing algorithms and ternary logic system, creation of a ternary structured programming system. Projects: Setun emulator, coding systems, chronometers, DSSP. Coverage of events in the field of ternary computing and logic. Publication of materials on the ternary symmetric number system, history of ternary computing.
copyright: "Trinary"
baseurl: "/"
url: "https://trinary.computer"
# twitter_username: ""
github_username:  trinarygroup

language_default: en
collections_dir: content
collections:
  en:
    output: true
    permalink: /:collection/:name
  ru:
    output: true
    permalink: /ru/:collection/:name

defaults:
  - scope:
      path: "_en"
    values:
      lang: en
  - scope:
      path: "_ru"
    values:
      lang: ru

# yandex_metrika: 169671

# Build settings
sass:
  sass_dir: assets/scss
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
