title: "Тринари"
email: ""
exceprt: "Троичная логика и троичная цифровая техника"
description: >
  Разработка троичных компьютерных систем, алгоритмов обработки информации и системы троичной логики, создание троичной системы структурированного программирования. Проекты: эмулятор Сетунь, системы кодирования, хронометры, ДССП. Освещение событий в области троичных вычислений и логики. Публикация материалов по троичной симметричной системе счисления, истории троичных вычислений.
baseurl: ""
url: "http://trinary.ru"
# twitter_username: ""
github_username:  trinarygroup
copyright: "Тринари"

yandex_metrika: 169671

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
